# Generated by Django 6.0.2 on 2026-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODETask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficients', models.JSONField(help_text='Coefficients for nonlinear terms in the ODE system')),
                ('x0', models.DecimalField(decimal_places=15, help_text='Initial value for x', max_digits=20)),
                ('y0', models.DecimalField(decimal_places=15, help_text='Initial value for y', max_digits=20)),
                ('z0', models.DecimalField(decimal_places=15, help_text='Initial value for z', max_digits=20)),
                ('w0', models.DecimalField(decimal_places=15, help_text='Initial value for w', max_digits=20)),
                ('target_time', models.DecimalField(decimal_places=15, help_text='Target time t_f', max_digits=20)),
                ('weighted_sum', models.DecimalField(blank=True, decimal_places=15, help_text='Weighted sum S', max_digits=20, null=True)),
                ('arc_length', models.DecimalField(blank=True, decimal_places=15, help_text='Arc length L', max_digits=20, null=True)),
                ('curvature', models.DecimalField(blank=True, decimal_places=15, help_text='Curvature κ at t_f', max_digits=20, null=True)),
                ('final_solution', models.IntegerField(blank=True, help_text='Final integer solution ℒ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the system was successfully solved')),
            ],
        ),
    ]
