# Generated by Django 6.0.2 on 2026-02-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ode_solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odetask',
            name='w_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final value for w at t_f', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='odetask',
            name='x_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final value for x at t_f', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='odetask',
            name='y_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final value for y at t_f', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='odetask',
            name='z_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final value for z at t_f', max_digits=20, null=True),
        ),
    ]
