# Generated by Django 6.0.2 on 2026-02-09 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ode_solver', '0002_odetask_w_final_odetask_x_final_odetask_y_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_output', models.TextField(help_text='Raw computational output from ODE solver')),
                ('latex_solution', models.TextField(help_text='AI-generated LaTeX solution string')),
                ('x_final', models.DecimalField(blank=True, decimal_places=12, help_text='Final value of x', max_digits=15, null=True)),
                ('y_final', models.DecimalField(blank=True, decimal_places=12, help_text='Final value of y', max_digits=15, null=True)),
                ('z_final', models.DecimalField(blank=True, decimal_places=12, help_text='Final value of z', max_digits=15, null=True)),
                ('w_final', models.DecimalField(blank=True, decimal_places=12, help_text='Final value of w', max_digits=15, null=True)),
                ('weighted_sum', models.DecimalField(blank=True, decimal_places=12, help_text='Weighted sum S = xf + 2*yf + 3*zf + 4*wf', max_digits=15, null=True)),
                ('arc_length', models.DecimalField(blank=True, decimal_places=12, help_text='Arc length L of the solution curve', max_digits=15, null=True)),
                ('curvature', models.DecimalField(blank=True, decimal_places=12, help_text='Curvature κ of the solution curve', max_digits=15, null=True)),
                ('final_solution', models.IntegerField(blank=True, help_text='Final calculated solution ℒ', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ode_task', models.ForeignKey(blank=True, help_text='Associated ODE task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='ode_solver.odetask')),
            ],
            options={
                'verbose_name': 'AI Solution',
                'verbose_name_plural': 'AI Solutions',
                'ordering': ['-created_at'],
            },
        ),
    ]
